# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: UA-193192572-1
# disqus-ID: x
# utterances-repo: x

links:
  slack: https://join.slack.com/t/layout-parser/shared_invite/zt-ohjd14k1-OrJ2HltwVRGrxhLeHMfW_w

assets:
  logo: '/assets/site/lp-logo.svg' 
  badge: '/assets/site/lp-badge-white.svg' 

menu:
- {name: 'Tutorials', file: '/tutorials.html'}
- {name: 'Docs', file: 'https://layout-parser.readthedocs.io/en/latest/'}
- {name: 'Discussion', file: 'https://join.slack.com/t/layout-parser/shared_invite/zt-ohjd14k1-OrJ2HltwVRGrxhLeHMfW_w'}

social:
# - {name: 'slack', icon: 'fab fa-slack-hash', link: ''}
- {name: 'Github', icon: 'fab fa-github', link: 'https://github.com/Layout-Parser/layout-parser'}

tutorials:
  categories:
    - {name: 'starter', title: 'Starter Example'}
    - {name: 'usecase', title: 'Use Cases'}

footnote: >
  Created and maintained by Layout Parser Developers. Built with [jekyll](https://jekyllrb.com/) and [bulma](http://bulma.io/).